<li class="list-none flex-column padding-max gray overflow-hidden" style="background: rgb(234, 234, 234);">
										<label>
											<h4 class="bold margin-bottom-min">PIN</h4>
											<h5 style="width: 526px;">Por motivos óbvios de segurança dos usuários, a toda alteração que você fizer que envolve dados pessoais é obrigatório você inserir seu PIN todas as vezes que esté tipo de alteração for realizada!</h5>
										</label>
										<div>
											<div id="pin-settings-area">
												<div class="flex margin-top-md" id="pin-inputs-area">
													<input class="margin-right-min" type="text" name="" placeholder="0" id="pin-input">
													<input class="margin-right-min" type="text" name="" placeholder="0" id="pin-input">
													<input class="margin-right-min" type="text" name="" placeholder="0" id="pin-input">
													<h4 class="margin-right-min margin-auto-top-bottom bold">-</h4>
													<input class="margin-right-min" type="text" name="" placeholder="0" id="pin-input">
													<input class="margin-right-min" type="text" name="" placeholder="0" id="pin-input">
													<input type="text" name="" placeholder="0" id="pin-input">
													<div class="margin-left-max">
														<button type="submit" class="blue-button" style="width: 100px;height: 40px;font-size: 14px;">
															<label class="margin-auto white">Validar</label>
														</button>
													</div>
												</div>
												<label class="general-error margin-top-md" style="width: 500px">
													<h6 class="margin-auto-top-bottom bold">O seu código pin está incorreto! Certifique-se de inserir-lo corretamente pois você tem apenas <b>3</b> tentativas até sua conta ser bloqueada.</h6>
												</label>
											</div>
										</div>
										<img style="position: absolute;width: 210px;height: 160px;right: -45px;bottom: -45px;" src="<?php echo $hotel['site']; ?>/general/assets/img/safetytips1_n.png">
									</li>